# Generated by Django 2.2.6 on 2019-11-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_abogado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abogado',
        ),
    ]
