# Generated by Django 2.2.6 on 2019-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_abogados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Abogados',
        ),
    ]
